// Device-test HTTPS overlay — used only by scripts/start-device-test.sh.
// Do not use in CI, production builds, or normal dev sessions.
// Requires DEVICE_TEST_CERT and DEVICE_TEST_KEY env vars (paths to self-signed
// cert/key PEM files generated by the launcher script).
import fs from "node:fs";
import { defineConfig, mergeConfig } from "vite";
import base from "./vite.config.ts";

const cert = process.env.DEVICE_TEST_CERT;
const key = process.env.DEVICE_TEST_KEY;
if (!cert || !key) {
  console.error("Device-test config requires DEVICE_TEST_CERT and DEVICE_TEST_KEY.");
  console.error("Use: bash scripts/start-device-test.sh");
  process.exit(1);
}

export default mergeConfig(
  base,
  defineConfig({
    server: {
      https: {
        cert: fs.readFileSync(cert),
        key: fs.readFileSync(key),
      },
    },
  }),
);
